UCSD:
    authurl: https://cruzroja.ucsd.edu/en/auth/token/
    url: https://cruzroja.ucsd.edu/en/api/
    username: admin
    password: cruzrojaadmin
EMSTrack:
    authurl: https://tijuana.emstrack.org/en/auth/token/
    url: https://tijuana.emstrack.org/en/api/
    username: test
    password: testuser